spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    com.a3solutions: INFO
    org.springframework.security: WARN

app:
  auth:
    allow-self-registration: false
    allow-admin-bootstrap: false
    bootstrap-admin:
      email: ""
      password: ""
