spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

app:
  bootstrap-demo-data: true
  auth:
    allow-self-registration: false
    allow-admin-bootstrap: true
    bootstrap-admin:
      email: admin@a3fsm.com
      password: admin123
