package com.a3solutions.fsm.timesheet;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * @author samuelkawuma
 * @package com.a3solutions.fsm.timesheet
 * @project A3 Field Service Management Backend
 * @date 07/03/26
 */
@Schema(description = "A completed work-order row attached to a weekly technician timesheet.")
public record TimesheetEntryResponse(
        @Schema(description = "Timesheet entry identifier.", example = "42")
        Long id,
        @Schema(description = "Completed work order represented by this entry.", example = "22")
        Long workOrderId,
        @Schema(description = "Date worked in the configured payroll timezone.", example = "2026-07-01")
        LocalDate workDate,
        @Schema(description = "Client or site customer name.", example = "Quest Diagnostics")
        String clientName,
        @Schema(description = "Street address or site floor/suite details.", example = "200 Forest Street 3rd Floor Ste A", nullable = true)
        String siteAddress,
        @Schema(description = "Service city.", example = "Marlborough", nullable = true)
        String city,
        @Schema(description = "Service state abbreviation.", example = "MA", nullable = true)
        String state,
        @Schema(description = "Service ZIP or postal code.", example = "01752", nullable = true)
        String zip,
        @Schema(description = "Technician-entered mileage for payroll/reimbursement.", example = "40.00", nullable = true)
        BigDecimal miles,
        @Schema(description = "Technician-entered onsite start time.", example = "08:00:00", nullable = true)
        LocalTime onsiteStartTime,
        @Schema(description = "Technician-entered break start time.", example = "12:00:00", nullable = true)
        LocalTime breakStartTime,
        @Schema(description = "Technician-entered break end time.", example = "12:30:00", nullable = true)
        LocalTime breakEndTime,
        @Schema(description = "Technician-entered offsite end time.", example = "16:00:00", nullable = true)
        LocalTime offsiteEndTime,
        @Schema(description = "Technician comments or completion notes.", example = "Reset control board and verified output.", nullable = true)
        String comments,
        @Schema(description = "Whether this row was automatically created from a completed work order.", example = "true")
        boolean autoGenerated,
        @Schema(description = "Timestamp when the entry was created.", example = "2026-07-01T20:05:00Z")
        Instant createdAt,
        @Schema(description = "Timestamp when the entry was last updated.", example = "2026-07-03T18:00:00Z")
        Instant updatedAt
) {
}
