package com.a3solutions.fsm.timesheet;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * @author samuelkawuma
 * @package com.a3solutions.fsm.timesheet
 * @project A3 Field Service Management Backend
 * @date 07/03/26
 */
public record TimesheetEntryResponse(
        Long id,
        Long workOrderId,
        LocalDate workDate,
        String clientName,
        String siteAddress,
        String city,
        String state,
        String zip,
        BigDecimal miles,
        LocalTime onsiteStartTime,
        LocalTime breakStartTime,
        LocalTime breakEndTime,
        LocalTime offsiteEndTime,
        String comments,
        boolean autoGenerated,
        Instant createdAt,
        Instant updatedAt
) {
}
