POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Deborah",
  "lastName": "Katimbo",
  "email": "debs@a3fsm.com",
  "password": "debs123",
  "role": "TECH"
}


###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
"firstName": "Samuel",
"lastName": "Kawuma",
"email": "sam@a3fsm.com",
"password": "sam123",
"role": "TECH"
}

